# Generated by Django 6.0.4 on 2026-04-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=100, unique=True)),
                ('flight_info', models.TextField(blank=True)),
                ('meal_preference', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='omnivore', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('yoga_class', 'Yoga Class'), ('juice_detox', 'Juice Detox'), ('massage', 'Massage'), ('breath_work', 'Breath Work')], max_length=20)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='guests.registration')),
            ],
            options={
                'unique_together': {('registration', 'activity')},
            },
        ),
    ]
